spring:
  cloud:
    nacos:
      #添加多个配置文件
      discovery:
        # 关闭默认访问本地 nacos
        enabled: true
        # nacos 服务发现 地址
        server-addr: ${configs.nacos.discovery.addr}
        # 命名空间，要先在 nacos 中配置好，然后把 uuid 粘贴过来
        namespace: ${configs.nacos.discovery.namespace}
        # 分组（默认分组）
        group: ${variableBase.nacos.group.default}

configs:
  swagger:
    # 文档标题
    title: 单点登录展示模块 swagger 接口文档
    # 电子邮箱
    email: daixu_cisco@sina.cn
    # 作者
    author: daixu
    # 版本号
    version: 1.1
    # 描述
    description: 单点登录模块接口文档




